print_info: False

# Frames
global_frame: "gps_origin"
uav_names: ["uav1", "uav2"]

# Dynamic constraints of the UAVs
dynamic_constraints:
  controller: "fast" # controller constraints
  tolerance: 0.01 # acceptable violation of constraints
  max_velocity:             
    x: 2.0 # (m/s)
    y: 2.0 # (m/s)
    z: 1.0 # (m/s)
  max_acceleration:             
    x: 2.0 # (m/s2)
    y: 2.0 # (m/s2)
    z: 1.0 # (m/s2)
  max_heading_rate:         0.5 # (rad/s)
  max_heading_acceleration: 1.0 # (rad/s^2)

# Trajectory parameters
trajectories:
  dt: 0.2 # (s)
  min_distance:
    mutual:    3.0 # (m)
    obstacles: 2.0 # (m)

  # UNUSED
  subscribe: True
  loading:
    folder: "/home/vit/git/mrs_camp_april2022/power_line_mockup_lausanne/trajectories"
    files:  ["trajectory_rotated_uav1.csv", "trajectory_rotated_uav47.csv", "trajectory_rotated_uav83.csv", "trajectory_rotated_uav7.csv"]

# Viewpoints specifications
viewpoints:
  distance: 4.0 # (m)

  inspection_limits:
    distance: 0.5 # (m)
    heading:  0.2 # (rad)
    pitch:    0.2 # (rad)

# Mission parameters
mission:
  timeout: 180.0 # (s)

solution_time_constraint:
  hard: 180.0
  soft: 60.0

# Cameras
cameras:
  red:
    angle_of_view:
      horizontal: 1.0 # (rad)
      vertical:   0.7 # (rad)
    fov_length:   2.0 # (m)

  blue:
    angle_of_view:
      horizontal: 1.0 # (rad)
      vertical:   0.5 # (rad)
    fov_length:   3.0 # (m)
