# A timeout between the takeoff being triggered and the UAV actually taking off
# while the timeout is counting down, the takeoff can be aborted by switching off
# the offboard mode.
# default = 5 sec
safety_timeout: 1.0 # [s]

topic_check:

  enabled: true
  timeout: 20.0 # [s], a window for the last accepted message

  # if "/" is provided at the beginning of topic_name, the topic name is considered as written,
  # if there is no "/" at the beginning, UAV_NAME is automatically added in from of the topic name (/uav1/topic_name)
  topics: [
    "odometry/uav_state",
    "control_manager/diagnostics",
    "/mrim_state_machine/ready_to_takeoff_1",
    "/mrim_state_machine/ready_to_takeoff_2"
  ]
