input_mode:
  actuators:             false
  control_group:         false
  attitude_rate:         false
  attitude:              false
  acceleration_hdg_rate: true
  acceleration_hdg:      false
  velocity_hdg_rate:     false
  velocity_hdg:          false
  position:              false

  feedforward: true

outputs:
  distance_sensor:      false
  gnss:                 true
  rtk:                  false
  imu:                  false
  altitude:             true
  magnetometer_heading: true
  rc_channels:          false
  battery_state:        false
  position:             true
  orientation:          true
  velocity:             true
  angular_velocity:     true
  odometry:             false
  ground_truth:         false
